name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential cmake vulkan-utils
    
    - name: Build
      run: make build-user
    
    - name: Run tests
      run: make test

  release:
    needs: test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    
    - name: Build release
      run: make build-user
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          target/release/mobilegpu-turbo
          install.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
